foodproject/foodapp/urls.py
from django.urls import path
from . import views
app_name='foodapp'
urlpatterns = [

    path('',views.home,name='home'),
    path('detail/<int:id>/',views.detail,name='detail'),
    path('add/',views.add,name='add'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

foodproject/foodproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('foodapp.urls'))
]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

foodproject/foodapp/models.py
from django.db import models

# Create your models here.
class Food(models.Model):
    name=models.CharField(max_length=150)
    desc=models.TextField()
    price=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

foodproject/foodapp/forms.py
from django import forms
from . models import Food
class Foodf(forms.ModelForm):
    class Meta:
        model=Food
        fields=['name','desc','price','img']

foodproject/foodapp/views.py
from django.shortcuts import render, redirect
from.models import Food
from.forms import Foodf
# Create your views here.
def home(request):
    food=Food.objects.all()
    return render(request,'index.html',{'food':food})
def detail(request,id):
    food=Food.objects.get(id=id)

    return render(request,'detail.html',{'food':food})
def add(request):
    if request.method=='POST':
        name=request.POST['name']
        desc=request.POST['desc']
        price=request.POST['price']
        img=request.FILES['img']
        food=Food(name=name,desc=desc,price=price,img=img)
        food.save()
        return redirect('/')
    return render(request,'add.html')
def update(request,id):
    food=Food.objects.get(id=id)
    form=Foodf(request.POST or None,request.FILES,instance=food)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'update.html',{'form':form})
def delete(request,id):
    food=Food.objects.get(id=id)
    food.delete()
    return redirect('/')

foodproject/templates/add.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
     <form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="name" placeholder="enter name"><br><br>
  <input type="text" name="desc" placeholder="enter desc"><br><br>
  <input type="number" name="price" placeholder="enter price"><br><br>
  <input type="file" name="img" placeholder="enterimage"><br><br>
  <input class="btn btn-primary" type="submit" value="Add Item">
  </form>
</div>


{% endblock %}

foodproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">



</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark" style="margin-bottom:50px">
  <a class="navbar-brand" href="#">
    <img src="{% static 'image/food.jpg' %}" width="30" height="30" class="d-inline-block align-top" alt="">
    ORDER FOOD
  </a>
    <a  href="add" class="navbar-brand btn btn-primary">Add Food</a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

foodproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{food.img.url}}" width="400px" height="400px">
        </div>
        <div class="col-md-6">
            <h1>{{food.name}}</h1>
            <h4>{{food.desc}}</h4>
            <h6>price:{{food.price}}</h6>
            <a class="btn btn-warning" href="{% url 'foodapp:update' food.id %}">update</a><br><br>
            <a class="btn btn-danger" href="{% url 'foodapp:delete' food.id %}">delete</a>
        </div>
    </div>

</div>



{% endblock %}

foodproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in food %}
        <div class="col-md-4">
          <div class="card" style="width: 18rem;">
            <img src="{{i.img.url}}" class="card-img-top" alt="..." width="200px" height="200px">
            <div class="card-body">
                <h5 class="card-title">{{i.name}}</h5>
                <p class="card-text">{{i.price}}</p>
                <a href="{% url 'foodapp:detail' i.id%}" class="btn btn-primary">click me</a>
            </div>
          </div>

        </div>
        {% endfor %}
    </div><br>

</div>


{% endblock %}

foodproject/templates/update.html
{% extends 'base.html' %}
{% block body %}
<div style="margin-left:50px">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>
</div>

{% endblock %}